version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ConsoleTableExt
    versions:
    - 3.0.0
    - 3.1.2
  - dependency-name: Microsoft.EntityFrameworkCore.Abstractions
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions
    versions:
    - 5.0.2
    - 5.0.3
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
