version: 2.0.{build}
image: Visual Studio 2019
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: dotnet build  -c Release EFCore.Taos.sln
artifacts:
- path: src\Maikebing.Data.Taos\bin\Release\Maikebing.Data.Taos.*.nupkg
  name: Maikebing.Data.Taos
- path: src\EFCore.Taos.Core\bin\Release\Maikebing.EntityFrameworkCore.Taos.*.nupkg
  name: Maikebing.EntityFrameworkCore.Taos
- path: src\Maikebing.HealthChecks.Taos\bin\Release\*.nupkg
  name: Maikebing.HealthChecks.Taos